name: CI
on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Spin up Miniconda & create the “stress” env from your YAML
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: stress

      # Run the project’s unit-tests
      - run: pytest -q
