name: CI

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Miniconda and create the environment
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: stress
          auto-activate-base: false

      # Explicitly install pytest inside the Conda env (even if it's in the YAML)
      - run: conda install pytest -y

      # Run unit tests
      - run: pytest -q
