name: CI

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Miniconda and create the environment
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: stress
          auto-activate-base: false  # prevents conflict with shell init

      # Run the unit tests inside the env using conda run
      - run: conda run -n stress pytest -q
