name: CI

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Conda environment
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: stress
          auto-activate-base: false

      # Ensure pytest is installed and package is registered
      - name: Install package and pytest
        run: |
          conda activate stress
          python -m pip install -e .
          python -m pip install pytest

      # Run unit tests
      - name: Run unit tests
        run: |
          conda activate stress
          pytest -q
