name: CI

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: stress
          auto-activate-base: false

      - run: conda run -n stress pip install -e .

      - run: conda run -n stress pytest -q
