name: CI
on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install -e .        # installs loan_stress & its deps

      - run: pip install pytest      # (keep existing line)
      - run: pytest -q
